apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: my-app
spec:
  selector:
    app: backend
  type: NodePort
  ports:
  - name: backend-svc
    protocol: TCP
    port: 8080
    targetPort: 8080
