apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: my-app
  name: mongo-pv
spec:
  capacity:
    storage: "1Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /app/data