pipeline{
    agent any
    parameters{
        string(name: 'BACKEND_DOCKER_TAG',defaultValue:'',description:'docker tag built by CI')
    }
    stages{
        stage('workspace cleanup'){
            steps{
                script{
                    cleanWs()
                }
            }
        }
        stage('Git: Checkoutcode'){
            steps{
                git "https://github.com/suryanshvermaa/complete_devops_project.git",branch: 'master'
            }
        }
        stage('Verify Docker Tags'){
            steps{
                script{
                    echo "BACKEND_DOCKER_TAG: ${params.BACKEND_DOCKER_TAG}"
                }
            }
        }
        stage('Update: Kubernetes manifests'){
            steps{
                script{
                    dir('k8s_manifests/backend'){
                        sh '''
                            sed -i -e s/suryanshverma/backend-server-app.*/suryanshverma/backend-server-app:${params.BACKEND_DOCKER_TAG}/g deployment.yml
                        '''
                    }
                }
            }
        }
        stage('Git: Code update and push to github'){
            steps{
                script{
                    withCredentials([gitUsernamePassword(credentialsId:'github',gitToolName:'Default')]){
                        sh '''
                            echo "Cjecking rrepository status: "
                            git status

                            echo "adding changes to git"
                            git add .
                            echo "commiting changes"
                            git commit -m "Updated environment variables"

                            echo "pushing changes to github"
                            git push https://github.com/suryanshvermaa/complete_devops_project.git master
                        '''
                    }
                }
            }
        }

    }
}